### ISSUE TITLE
Will Fitzgerald: Movie Synopses of Movies that kinda don't exist yet

### ISSUE THREAD

**Issue by willf** [NaNoGenMo/2021#22]
Using real titles from 1920 movies, as well as the genre, director, and stars, I've generate synopses of movies that don't quite exist.

**Comment by willf** [comment]
Using real titles from 1920 movies, as well as the genre, director, and stars, I've generated 610 synopses of movies that don't quite exist.


And here are the results! https://github.com/willf/NaNoGenMo-2021/blob/main/nanogenmo2021.md

For example:

_Behold My Wife!_ is a drama movie directed by George Melford. It stars Mabel Julienne Scott, Milton Sills, and Winter Hall.

**Synopsis**: The movie is about Morgan Wessel, a young painter who has fallen out of love with his work. He spends his days grieving for what he perceives as his undoing- an unfinished masterpiece, "The Blind Child's Dream". When the boy's father dies, Morgan returns to Scotland to find him, and meets up with art connoisseur Hector Waring at the hotel. Waring admires Morgan's painting, and invites him to come to stay with him. When he arrives at Waring's house, he's disappointed to find out that Waring is recently widowed. He also discovers that the epitaph for his painting he wrote is Latin, and he must learn the language to read it. They eventually marry so Morgan can finish his masterpiece.

**Comment by hugovk** [comment]
Link to source: https://github.com/willf/NaNoGenMo-2021 🎥

**Comment by verachell** [comment]
This project is awesome!! I love it!! My favorite one of your movies is Alarm Clock Andy, the synopsis is hilarious. It's great that you included the Wikipedia links to the originals in your final novel, I loved seeing how your generated plots are totally different.
