### ISSUE TITLE
Intend to participate

### ISSUE THREAD

**Issue by makeworld-the-better-one** [NaNoGenMo/2021#26]
I'd love to participate for the first time in NaNoGenMo! It seems like a great fun idea.

I'll update this thread once I pick an idea, still germinating one right now. I've made markov chain bots before, so maybe I could do something unique with those. I'm also intrigued by the idea of combining existing written sources (Wikipedia, free books, forums, Reddit, etc) into some sort of narrative.

**Comment by makeworld-the-better-one** [comment]
## Ideas

- Scrape erotic works of fiction (from literotica etc) but remove any erotic or offensive words, or maybe the whole sentence
- Create new fiction plots by taking plot summary paragraphs from Wikipedia, and splicing them with other articles with plot summaries that are linked
	- Base article (A) is picked and first paragraph of plot is used
	- Next paragraph comes from the second paragraph of the plot section of the first article linked in A with a plot summary
	- Etc

Feel free to let me know if any of these ideas have been done already.

**Comment by enkiv2** [comment]
I don't think exactly these things have been done before. There's a corpus
of wikipedia plot summaries floating around (I think it made its way into a
previous resource thread, but if you can't find it, let me know because I
have a local copy).

**Comment by makeworld-the-better-one** [comment]
> There's a corpus of wikipedia plot summaries floating around

[Found it](https://github.com/markriedl/WikiPlots), thanks. If I'm going to scrape for article links anyway it might not be useful, but poking around the code could be helpful maybe.

I've also found an OkCupid Essay data set (almost 60k answers) with the following categories:

- My self summary
- What I’m doing with my life
- I’m really good at
- The first thing people usually notice about me
- Favorite books, movies, show, music, and food
- The six things I could never do without
- I spend a lot of time thinking about
- On a typical Friday night I am
- The most private thing I am willing to admit
- You should message me if...

Using those for a markov chain or LSTM/RNN would be fun.

**Comment by lee2sman** [comment]
Check out the artist Sue Huang's [Erotic Ecologies](http://www.sue-huang.com/#/erotic-ecologies/) project! You may dig it and it may prompt some ideas.

**Comment by makeworld-the-better-one** [comment]
Thanks! Looks like an amazing project.

I've started work on Wikipedia plots idea, but lost steam somewhat. I'll see where it goes and what I have time for.

**Comment by makeworld-the-better-one** [comment]
Well looks like it didn't end up working out. Thanks for everyone's help, and I still love the idea of NaNoGenMo. Maybe next year!
