### ISSUE TITLE
Mezangeller

### ISSUE THREAD

**Issue by amirouche** [NaNoGenMo/2021#51]
I intend to work on program that turn a text into somekind of [`search://mezangelle`](https://duckduckgo.com/?q=mezangelle).

I read the rules at https://nanogenmo.github.io/:

> The "novel" is defined however you want. It could be 50,000 repetitions of the word "meow". It could literally grab a random novel from Project Gutenberg. It doesn't matter, as long as it's 50k+ words. 

It seems ok if the preview is based on an essay?

**Comment by enkiv2** [comment]
Yes. If you write a program that somehow emits 50k words, it will get a
'completed' tag. It doesn't matter where the words come from (although
that's the most interesting thing about an entry generally), and the words
don't even really need to be 'real'.

**Comment by amirouche** [comment]
Thanks @enkiv2. I would prefer to use one of your essay as the primary material, one of those:

- https://enkiv2.medium.com/software-vs-capital-e8ab15b48390
- https://enkiv2.medium.com/free-software-and-the-revolt-against-transactionality-3a44a1b7f96d
- https://enkiv2.medium.com/freeing-software-3e3ede439f20

I can't find a license information about those. Do you agree for me to use one of those essay? Under what license?

**Comment by enkiv2** [comment]
You're welcome to do whatever with those :)

**Comment by MichaelPaulukonis** [comment]
Also something I have thought about working on for 10+ years and Never Quite Got Around To It.

Some related theories and xrefs at [gnoetry daily](https://gnoetrydaily.wordpress.com/2011/01/11/codework-parenthetical-insertions)

**Comment by amirouche** [comment]
That is very nice:
![screenshot-2021-11-11T20:33:13+01:00](https://user-images.githubusercontent.com/7444897/141357798-6ab58ed6-a469-4856-bd65-af33c3d27f22.jpg)

Thanks for the link @MichaelPaulukonis

**Comment by amirouche** [comment]
I could not finish the project, maybe next round!

Thanks for the interest and insightful input, and project. See you at next nanogenmo!
